POST http://localhost:3000/articles HTTP/1.1
content-type: application/json

{
    "title":"unfold",
    "description" :"kitty"
}
###
POST http://localhost:3000/articles/0/comments HTTP/1.1
content-type: application/json

{
    "author":"foo",
    "body" :"bar"
}
###
GET http://localhost:3000/articles HTTP/1.1

###

DELETE http://localhost:3000/articles/-1 HTTP/1.1
content-type: application/json

{
    "title":"unfold"
}